package model;
// Generated 22 mars 2022, 09:10:07 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BonReduction generated by hbm2java
 */
@Entity
@Table(name = "bon_reduction", catalog = "caisse")
public class BonReduction implements java.io.Serializable {

	private int numBon;
	private int prixBon;
	private Date dateExpiration;

	public BonReduction() {
	}

	public BonReduction(int numBon, int prixBon, Date dateExpiration) {
		this.numBon = numBon;
		this.prixBon = prixBon;
		this.dateExpiration = dateExpiration;
	}

	@Id

	@Column(name = "NumBon", unique = true, nullable = false)
	public int getNumBon() {
		return this.numBon;
	}

	public void setNumBon(int numBon) {
		this.numBon = numBon;
	}

	@Column(name = "PrixBon", nullable = false)
	public int getPrixBon() {
		return this.prixBon;
	}

	public void setPrixBon(int prixBon) {
		this.prixBon = prixBon;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateExpiration", nullable = false, length = 10)
	public Date getDateExpiration() {
		return this.dateExpiration;
	}

	public void setDateExpiration(Date dateExpiration) {
		this.dateExpiration = dateExpiration;
	}

}
